import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { BookmarkProvider } from "./context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Troylab Task",
  description: "Generated by Ahmed Goda",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <BookmarkProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </BookmarkProvider>
  );
}
